### ISSUE TITLE
Error: all(file.exists(files)) is not TRUE

### ISSUE THREAD

**Issue by cartal** [mikelove/tximport#17]
Hi

I'm working with some Salmon files using mouse RNA-Seq. I have followed the steps of the vignette  and it seems to work, until I reach the tximport step when I run the following command:

**txi.salmon <- tximport(files, type = "salmon", tx2gene = tx2gene, reader = read_tsv)**

I get the following error:

**Error: all(file.exists(files)) is not TRUE**

I am not sure if this is an issue with _tximport_ or with my own data.

My tx2gene looks like this:

**TXNAME,GENEID
ENSMUSG00000064372,mt-Tp
ENSMUSG00000064371,mt-Tt
ENSMUSG00000064370,mt-Cytb
ENSMUSG00000064369,mt-Te**

and my files looks like this:

                                                                                                       sample_1
"~/Documents/data/samples/deconv//salmon/sample_1/quant.genes.sf"
                                                                                                       sample_2
"~/Documents/data/samples/deconv//salmon/sample_2/quant.genes.sf"
                                                                                                        sample_3
"~/Documents/data/samples/deconv//salmon/sample_3/quant.genes.sf"

Thanks in advance for pointing out to a solution or a glaring error from my side.

Regards

**Comment by mikelove** [comment]
hi,

As this software moved to Bioconductor, the appropriate place for asking software questions is: support.bioconductor.org

But I can tell you, your problem here is that you need to specify a correct path to your files. `all(file.exists(files))` is not TRUE means that the paths in `files` are not correct. 

Please post any follow up or future questions to support.bioconductor.org
